# Generated by Django 6.0.6 on 2026-06-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('half_day', 'Half Day'), ('full_day', 'Full Day')], default='hourly', max_length=20),
        ),
    ]
