# Generated by Django 6.0.6 on 2026-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='half_day_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20, null=True),
        ),
    ]
