# Generated by Django 6.0.6 on 2026-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_booking_half_day_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='membership_type',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non Member')], default='non_member', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
