# Generated by Django 6.0.6 on 2026-06-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booking_membership_type_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_complimentary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
