# Generated by Django 6.0.5 on 2026-07-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_booking_user_alter_booking_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
