# Generated by Django 6.0.5 on 2026-07-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
